# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

model:
  - midas_256.bin,file:///home/ubuntu/midas_256.bin
  - yolo11n-seg-w8a16-qcs9075.bin,file:///home/ubuntu/yolo11n-seg-w8a16-qcs9075.bin
  - yolo11n-seg-w8a16-qcs8275-proxy.bin,file:///home/ubuntu/yolo11n-seg-w8a16-qcs8275-proxy.bin

apt:
  - ros-jazzy-qrb-ros-camera
  - ros-jazzy-qrb-ros-nn-inference
  - ros-jazzy-qrb-ros-tensor-list-msgs
  - ros-jazzy-image-publisher
  - ros-jazzy-cv-bridge
  - python3-numpy

pip:
