#AI model
model:
  - MediaPipeFaceDetector.bin,https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceDetector.bin
  - MediaPipeFaceLandmarkDetector.bin,https://huggingface.co/qualcomm/MediaPipe-Face-Detection/resolve/0dd669a326ec24a884e51b82741997299d937705/MediaPipeFaceLandmarkDetector.bin
  - anchors_face.npy,https://raw.githubusercontent.com/zmurez/MediaPipePyTorch/65f2549ba35cd61dfd29f402f6c21882a32fabb1/anchors_face.npy

# apt packages
apt:
  - ros-jazzy-cv-bridge
  - ros-jazzy-image-publisher
  - python3-opencv

# python packages
pip:

