# This config file is used by ros2_control
/**/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz (reduced from 100Hz to reduce system load)

    rm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/rm_group_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

/**/hand_controller:
  ros__parameters:
    joints:
      - joint01
      - joint11
      - joint02
      - joint22
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false