image_width: 640
image_height: 480
camera_name: "narrow_stereo"
camera_matrix:
  rows: 3
  cols: 3
  data: [595.56349,   0.     , 351.43901,
           0.     , 594.34396, 212.79984,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.182680, -0.232973, -0.014358, 0.020141, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [616.05768,   0.     , 361.61694,   0.     ,
           0.     , 622.09174, 207.08056,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
