# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# Copyright (c) 2026, Qualcomm Innovation Center, Inc. and/or its affiliates.
# All rights reserved.


uint32 x_bbox
uint32 y_bbox
uint32 width_bbox
uint32 height_bbox
uint32 x_right_eye
uint32 y_right_eye
uint32 x_left_eye
uint32 y_left_eye
uint32 x_nose_tip
uint32 y_nose_tip
uint32 x_right_corner
uint32 y_right_corner
uint32 x_left_corner
uint32 y_left_corner
float32 face_score
string name