<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="qrb_robot_base_diff_drive" params="ns:='' wheel_separation separation_multiplier:=1 
    wheel_radius radius_multiplier:=1 update_rate:=30 ">
    <xacro:property name="namespace" value="${ns + '/' if ns != '' else ''}" />
    <gazebo>
      <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <right_joint>${namespace}wheel_right_joint</right_joint>
        <left_joint>${namespace}wheel_left_joint</left_joint>
        <wheel_separation>${wheel_separation*separation_multiplier}</wheel_separation>
        <wheel_radius>${wheel_radius*radius_multiplier}</wheel_radius>
        <odom_publish_frequency>${update_rate}</odom_publish_frequency>
        <topic>${namespace}cmd_vel</topic>
        <odom_topic>${namespace}odom</odom_topic>
        <frame_id>${namespace}odom</frame_id>
        <child_frame_id>${namespace}base_footprint</child_frame_id>
        <tf_topic>tf</tf_topic>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>