# Default initial positions for rml_63's ros2_control fake system

initial_positions:
  joint01: 0
  joint02: 0
  joint1: 0
  joint11: 0
  joint2: 0
  joint22: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0