# depth camera parameters
sensor_name: "depth_camera"
update_rate: 15
camera:
  horizontal_fov: 1.570796
  image:
    width: 640
    height: 360
  depth_camera:
    clip:
      near: 0.02
      far: 20
  noise:
    type: "gaussian"
    mean: 0
    stddev: 0.003
always_on: 1
visualize: "true"
topic: "camera/depth"