name: QIRP Build Test

on: [push, pull_request]

jobs:
  qirp-sdk-build-checker:
    uses: qualcomm-qrb-ros/.github/.github/workflows/qirp-sdk-build-checker.yml@qirp-sdk-build
    with:
      pre_build_commands: | 
        find ${WORKSPACE} -name "build.sh" -type f -exec bash {} \;