name: Sync Debian Branches

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: qualcomm-qrb-ros/.github/.github/workflows/sync-debian.yml@sync_debian_branch
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
